CREATE DATABASE ClearNoteDB

USE ClearNoteDB

CREATE TABLE Category (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CategoryName VARCHAR(20) NOT NULL
)

CREATE TABLE NoteLayout (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	BackgroundColour VARCHAR(20) NULL,
	TextColour VARCHAR(20) NULL
)



CREATE TABLE [User] (
	ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	[Password] VARCHAR(20) NOT NULL,
	PhoneNumber INT NULL
)

CREATE TABLE Task (
	TaskID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT FOREIGN KEY REFERENCES [User](UserID) NOT NULL,
	Title VARCHAR(30) NOT NULL,
	DueDate DATE NOT NULL,
	CompletionDate DATE NOT NULL,
	[Status] BIT NOT NULL
)


CREATE TABLE Note (
	NoteID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	UserID INT FOREIGN KEY REFERENCES [User](UserID) NOT NULL,
	CategoryID INT FOREIGN KEY REFERENCES Category(CategoryID) NOT NULL,
	Title VARCHAR(30) NOT NULL,
	DateOfCreation DATE NOT NULL,
	LastModified DATE NOT NULL
)